name: 📦 Publish try-handler

on:
  push:
    branches:
      - main
    paths:
      - 'apps/try-handler/package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: install dependencies
        run: pnpm install --no-link-workspace-packages --no-frozen-lockfile

      - name: build
        run: pnpm build

      - name: testing
        run: pnpm test
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if version changed
        id: check_version
        run: |
          VERSION_CHANGED=$(git diff HEAD^ HEAD -- 'apps/try-handler/package.json' | grep '"version":' || true)
          if [ -z "$VERSION_CHANGED" ]; then
            echo "Version has not changed. Skipping..."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Version has changed. Running job..."
            echo "skip=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: setup node
        if: ${{ env.skip == 'false' }}
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: setup pnpm
        if: ${{ env.skip == 'false' }}
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: install dependencies
        if: ${{ env.skip == 'false' }}
        run: pnpm install --no-link-workspace-packages --no-frozen-lockfile

      - name: build
        if: ${{ env.skip == 'false' }}
        run: pnpm build

      - name: registry
        if: ${{ env.skip == 'false' }}
        run: npm set registry=https://registry.npmjs.org/

      - name: publish
        if: ${{ env.skip == 'false' }}
        run: |
          cd apps/try-handler
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
